keyword = 'spotify'
exit_phrase = f'{keyword} închide'
play_phrase = 'spotify pune'
play_playlist_phrase = ['spotify redă playlistul', 'spotify redă playlist ul', 'spotify redă playlist all']
pause_phrase = ['spotify stop', 'spotify pauză']
previous_phrase = 'spotify înapoi'
next_phrases = ['spotify următorul', 'spotify următoarea']
resume_phrase = 'spotify continu'
increase_volume = 'spotify mai tare'
decrease_volume = 'spotify mai încet'
