keyword = 'andrei'
exit_phrase = f'{keyword} închide'
play_phrase = f'{keyword} pune'
play_playlist_phrase = [f'{keyword} redă playlistul', f'{keyword} redă playlist ul', f'{keyword} redă playlist all']
pause_phrase = [f'{keyword} stop', f'{keyword} pauză']
previous_phrase = f'{keyword} înapoi'
next_phrases = [f'{keyword} următorul', f'{keyword} următoarea']
resume_phrase = f'{keyword} continu'
increase_volume = f'{keyword} mai tare'
decrease_volume = f'{keyword} mai încet'
